using System.Security.Cryptography;using System.Text;using DeliveryEntity=LocalCommerce.Domain.Delivery.Delivery;using DeliveryEntityStatus=LocalCommerce.Domain.Delivery.DeliveryStatus;
using LocalCommerce.Application.Idempotency;
namespace LocalCommerce.Application.Delivery;
public sealed record CreateReplacementDeliveryCommand(Guid OrderId,Guid StoreId,Guid ActorId,string IdempotencyKey);
public sealed record CreateReplacementDeliveryResult(Guid DeliveryId);public sealed class CreateReplacementDeliveryRejectedException:Exception{public CreateReplacementDeliveryRejectedException(string m):base(m){}}
public interface ICreateReplacementDeliveryRepository{Task<DeliveryEntity?> GetActiveByOrderIdAsync(Guid orderId,CancellationToken ct);Task AddAsync(DeliveryEntity delivery,CancellationToken ct);}
public interface IReplacementDeliveryEligibility{Task<bool> IsOrderEligibleAsync(Guid orderId,CancellationToken ct);}
public interface IIdempotencyStore{Task<CreateReplacementDeliveryIdempotencyRecord?> GetAsync(Guid actorId,string operation,string key,CancellationToken ct);Task<CreateReplacementDeliveryIdempotencyRecord?> ReserveAsync(Guid actorId,string operation,string key,string fingerprint,CancellationToken ct);Task CompleteAsync(Guid actorId,string operation,string key,CreateReplacementDeliveryResult result,CancellationToken ct);}
public interface ICreateReplacementDeliveryUnitOfWork{Task ExecuteAsync(Func<CancellationToken,Task> operation,CancellationToken ct);}
public sealed class CreateReplacementDeliveryHandler{
 const string Operation="CreateReplacementDelivery";readonly ICreateReplacementDeliveryRepository _r;readonly IReplacementDeliveryEligibility _e;readonly ICreateReplacementDeliveryIdempotencyStore _i;readonly ICreateReplacementDeliveryUnitOfWork _u;
 public CreateReplacementDeliveryHandler(ICreateReplacementDeliveryRepository r,IReplacementDeliveryEligibility e,ICreateReplacementDeliveryIdempotencyStore i,ICreateReplacementDeliveryUnitOfWork u){_r=r;_e=e;_i=i;_u=u;}
 public async Task<CreateReplacementDeliveryResult> HandleAsync(CreateReplacementDeliveryCommand c,CancellationToken ct=default){
  if(c.OrderId==Guid.Empty||c.StoreId==Guid.Empty||c.ActorId==Guid.Empty)throw new CreateReplacementDeliveryRejectedException("Order, Store and Actor are required.");if(string.IsNullOrWhiteSpace(c.IdempotencyKey))throw new CreateReplacementDeliveryRejectedException("Idempotency key is required.");
  var fp=Convert.ToHexString(SHA256.HashData(Encoding.UTF8.GetBytes($"{c.OrderId:N}|{c.StoreId:N}|{c.ActorId:N}")));var old=await _i.GetAsync(c.ActorId,Operation,c.IdempotencyKey,ct);if(old is not null)return Resolve(old,fp);
  if(!await _e.IsOrderEligibleAsync(c.OrderId,ct))throw new CreateReplacementDeliveryRejectedException("Order is not eligible for replacement delivery.");
  if(await _r.GetActiveByOrderIdAsync(c.OrderId,ct) is not null)throw new CreateReplacementDeliveryRejectedException("An active Delivery already exists.");
  CreateReplacementDeliveryResult? result=null;await _u.ExecuteAsync(async tx=>{var reserved=await _i.ReserveAsync(c.ActorId,Operation,c.IdempotencyKey,fp,tx);if(reserved is not null){result=Resolve(reserved,fp);return;}if(!await _e.IsOrderEligibleAsync(c.OrderId,tx))throw new CreateReplacementDeliveryRejectedException("Order is not eligible for replacement delivery.");if(await _r.GetActiveByOrderIdAsync(c.OrderId,tx) is not null)throw new CreateReplacementDeliveryRejectedException("An active Delivery already exists.");var d=DeliveryEntity.Create(c.OrderId,c.StoreId);await _r.AddAsync(d,tx);result=new CreateReplacementDeliveryResult(d.Id);await _i.CompleteAsync(c.ActorId,Operation,c.IdempotencyKey,new IdempotencyCompletion("Delivery", result.DeliveryId, System.Text.Json.JsonSerializer.Serialize(result)),,tx);},ct);return result??throw new InvalidOperationException("Replacement delivery completed without a result.");
 }
 static CreateReplacementDeliveryResult Resolve(IdempotencyRecord x,string fp){if(x.Fingerprint!=fp)throw new CreateReplacementDeliveryRejectedException("Idempotency key was already used with a different request.");if(x.Result.DeliveryId==Guid.Empty)throw new CreateReplacementDeliveryRejectedException("Idempotency record is incomplete.");return x.Result;}
}